# action.yml
name: 'Generate Diff Command'
description: 'Create command based from passed params as required'
inputs:
  build_mode: # id of input
    description:
    required: true
    default: 'feature'
  build_environment: # id of input
    description:
    required: true
    default: 'uat'
  deploy_diff: # id of input
    description:
    required: false
    default: ''
  build_refresh_days: # id of input
    description:
    required: false
    default: '14'

outputs:
  diff_cmd: # id of output
    description: 'Generated diff command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_mode }}
    - ${{ inputs.build_environment }}
    - ${{ inputs.deploy_diff }}
    - ${{ inputs.build_refresh_days }}
